In [64]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt
from dotenv import load_dotenv
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
# load_dotenv()

# GPT_API_KEY = os.getenv("GPT_API_KEY")

# llm = GPTModel(GPT_API_KEY, "gpt-3.5-turbo-0125", 0.7)

In [66]:
cec2017_tasks = get_2_tasks(0)

In [67]:
num_indis_per_task = 50
indi_len = 50
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation, eta=20)
# crossover = BLXCrossover()
rmp = AdaptiveRMPMatrix(rmp_pop_size=4, num_gen=3, pc=0.8, pm=0.1)

np.random.seed(0)
amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 34.629614718853325
Mean Fitness: 43.33345570014081

Task 1:
Best Fitness: 28389.17824247567
Mean Fitness: 41755.594589612476



In [68]:
bfs, mfs = amfea.fit(num_gen=200,monitor=True, monitor_rate=10, llm_rate=100)

Creating strategy
Evaluating strategy
Strategy: 
Calculate the Euclidean distance between the mean vectors of each task to quantify the difference in average positions. Adjust RMP values inversely proportional to the distance, so tasks with more similar mean vectors have higher RMP values.
Compute the Mahalanobis distance between the population variance matrices of each task to capture the difference in distribution spread. Adjust RMP values based on the Mahalanobis distance, with tasks having more similar spread having higher RMP values.
Perform a principal component analysis (PCA) on the population variance matrices of tasks to identify the dominant directions of diversity. Adjust RMP values based on the alignment of these principal components, with tasks having similar diversity directions having higher RMP values.
Apply a clustering algorithm to group tasks based on their population statistics, then adjust RMP values within clusters to be higher than those between clusters. This en

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Evaluating strategy
Strategy: 
Calculate the Euclidean distance between the mean vectors of each pair of tasks. Adjust RMP values inversely proportional to the distance: the closer the means, the higher the RMP.
Compute the Mahalanobis distance between the mean vectors of each pair of tasks using the population variances. Adjust RMP values inversely proportional to the Mahalanobis distance.
Assess the cosine similarity between the mean vectors of each pair of tasks. Adjust RMP values proportionally to the cosine similarity: the higher the similarity, the higher the RMP.
Compare the variance values of each task and adjust RMP values inversely proportional to the variance: tasks with higher variance should have lower RMP values.
Creating code...
RMP function: import numpy as np

def get_rmp_matrix(task_count, pop_mean, pop_variance):
    rmp_matrix = np.zeros((task_count, task_count))
    
    for i in range(task_count):
        for j in range(i, task_count):
            euclidean_distan

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 20
Evaluation count: 0
Task 0, Best: 12.32478130118894, Avg: 13.176068189013069
Task 1, Best: 12021.280541802837, Avg: 12955.14004009907
Time taken each gen: 0.0125 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Adapt

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 40
Evaluation count: 0
Task 0, Best: 9.059674750226414, Avg: 9.435620576466041
Task 1, Best: 8448.334214314142, Avg: 8856.678297718314
Time taken each gen: 0.0171 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Adaptiv

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 60
Evaluation count: 0
Task 0, Best: 7.213400175286383, Avg: 7.382549209479188
Task 1, Best: 6633.161247534565, Avg: 6921.173821793257
Time taken each gen: 0.0110 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Adaptiv

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 80
Evaluation count: 0
Task 0, Best: 5.471020245920514, Avg: 5.636267203850482
Task 1, Best: 4954.876427412704, Avg: 5119.106243779945
Time taken each gen: 0.0203 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Adaptiv

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Crossover...
Evaluating strategy
Strategy: 
Calculate the cosine similarity between the population mean vectors of each pair of tasks. Adjust RMP values proportionally to the similarity, with more similar tasks having higher mating probabilities.
Analyze the correlation matrix of the population variances for each pair of tasks. Adjust RMP valu

d:\ANACONDA\Lib\site-packages\sklearn\decomposition\_pca.py:653: RuntimeWarning: invalid value encountered in divide
  explained_variance_ratio_ = explained_variance_ / total_var
d:\ANACONDA\Lib\site-packages\sklearn\decomposition\_pca.py:653: RuntimeWarning: invalid value encountered in divide
  explained_variance_ratio_ = explained_variance_ / total_var


Evaluating strategy
Strategy: 
Utilize a Pearson correlation analysis on the population means of each task to quantify the linear relationship between tasks. Adjust RMP values proportionally to the correlation coefficient, with highly correlated tasks having higher RMP values.
Apply a hierarchical clustering algorithm on the population variances of each task to identify groups of tasks with similar spread. Adjust RMP values within each cluster to be higher and between clusters to be lower.
Calculate the Jensen-Shannon divergence between the probability distributions of each pair of tasks based on the kernel density estimation of population variances. Adjust RMP values inversely proportional to the divergence, with more divergent tasks having lower RMP values.
Perform a principal component analysis on the population means and variances to identify the major sources of variance between tasks. Adjust RMP values based on the principal components, giving higher weight to components that exp

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Evaluating strategy
Strategy: 
Calculate the Euclidean distance between the population mean vectors of each pair of tasks. Adjust RMP values inversely proportional to the distance, with closer tasks having higher mating probabilities.
Analyze the covariance matrix of the population variances for each pair of tasks. Adjust RMP values based on the strength of covariance, with tasks having higher covariance having higher mating probabilities.
Perform a cluster analysis on the population variances of tasks to identify groups of tasks with similar variance patterns. Adjust RMP values based on the cluster assignments, giving higher probabilities to tasks within the same cluster.
Estimate the Kullback-Leibler divergence between the probability distributions of each pair of tasks to measure the difference in information content while penalizing deviations from the overall distribution shape. Adjust RMP values based on the Kullback-Leibler divergence, assigning higher mating probabilities to ta

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 130
Evaluation count: 0
Task 0, Best: 2.828863069468281, Avg: 2.883498390038746

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 140
Evaluation count: 0
Task 0, Best: 2.4052208615539517, Avg: 2.58224416566961

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]


d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 180
Evaluation count: 0
Task 0, Best: 1.7943906248813772, Avg: 1.8552458357863935
Task 1, Best: 1262.2738786038076, Avg: 1310.6258528099781
Time taken each gen: 0.0276 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Ad

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]


d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than availabl

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Gen 190
Evaluation count: 0
Task 0, Best: 1.6614262136386095, Avg: 1.7061274819332033
Task 1, Best: 1040.4498848768592, Avg: 1129.382851310556
Time taken each gen: 0.0381 seconds

Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Error in creating RMP matrix: 'Ada

d:\ANACONDA\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Error in creating RMP matrix: 'AdaptiveRMPMatrix' object has no attribute 'validate_rmp_matrix'
RMP_Matrix:
[[1.  0.3]
 [0.3 1. ]]
Crossover...
Evaluating strategy
Strategy: 
Calculate the Euclidean distance between the population mean vectors of each pair of tasks. Adjust RMP values inversely proportional to the distance, with closer tasks having higher mating probabilities.
Analyze the covariance matrix of the population variances for each pair of tasks. Adjust RMP values based on the strength of covariance, with tasks that exhibit similar variance patterns having higher mating probabilities.
Perform a multidimensional scaling (MDS) on the population variances of tasks to visualize the pairwise distances in a lower-dimensional space. Adjust RMP values based on the MDS distances, giving higher probabilities to tasks that cluster together.
Estimate the Bhattacharyya distance between the probability distributions of each pair of tasks to capture the overlap in their distributions. Adjus

In [69]:
# num_tasks = len(tasks)
# fig, axes = plt.subplots(num_tasks, 2)
# fig.tight_layout()
# for i in range(num_tasks):
#     axes[i][0].plot(bfs[i])
#     axes[i][1].plot(mfs[i])