In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt
from dotenv import load_dotenv
import os

In [2]:
def _mutate(genes, dim_uss, pm, nm):
    idx_mutation = np.where(np.random.rand(dim_uss) <= pm)[0]

    u = np.zeros((dim_uss,)) + 0.5
    u[idx_mutation] = np.random.rand(len(idx_mutation))

    delta = np.where(u < 0.5,
        # delta_l
        (2*u)**(1/(nm + 1)) - 1,
        # delta_r
        1 - (2*(1-u))**(1/(nm + 1))
    )

    return np.where(delta < 0,
                # delta_l: ind -> 0
                # = genes * (delta + 1)
                genes + delta * genes,
                # delta_r: ind -> 1
                # = genes (1 - delta) + delta
                genes + delta * (1 - genes)
            )

In [3]:
dim = 50
x = np.random.uniform(0, 1, size=dim)

In [4]:
x

array([0.99018855, 0.05951667, 0.29687793, 0.92357362, 0.08568084,
       0.85524941, 0.07055279, 0.90077335, 0.54488147, 0.62193085,
       0.38807626, 0.48939937, 0.935219  , 0.60035485, 0.88317273,
       0.73216711, 0.29755535, 0.67654747, 0.04812882, 0.68090822,
       0.5420188 , 0.5480054 , 0.95512734, 0.97471169, 0.15487518,
       0.10842618, 0.22118335, 0.05780146, 0.83563523, 0.18728424,
       0.27444001, 0.91975364, 0.89117652, 0.5262705 , 0.84891004,
       0.192538  , 0.77970622, 0.31471084, 0.11993691, 0.87281803,
       0.395529  , 0.92102977, 0.99547516, 0.56230939, 0.33124808,
       0.20684087, 0.41927536, 0.35343746, 0.06611581, 0.06283178])

In [161]:
_mutate(x, dim, 0.02, 5)

array([0.80833198, 0.05951667, 0.29687793, 0.92357362, 0.08568084,
       0.85524941, 0.07055279, 0.90077335, 0.54488147, 0.62193085,
       0.38807626, 0.48939937, 0.935219  , 0.60035485, 0.88317273,
       0.73216711, 0.29755535, 0.67654747, 0.04812882, 0.68090822,
       0.5420188 , 0.5480054 , 0.95512734, 0.97471169, 0.15487518,
       0.10842618, 0.22118335, 0.05780146, 0.83563523, 0.18728424,
       0.27444001, 0.91975364, 0.89117652, 0.5262705 , 0.86397388,
       0.192538  , 0.77970622, 0.31471084, 0.11993691, 0.87281803,
       0.395529  , 0.92102977, 0.99547516, 0.56230939, 0.33124808,
       0.20684087, 0.41927536, 0.35343746, 0.06611581, 0.06283178])

In [8]:
m = PolynomialMutation(5, 0.02)
_x = m(np.array([x]), [1])
print(_x)

(array([[0.99018855, 0.05951667, 0.29687793, 0.92357362, 0.08568084,
        0.85524941, 0.07055279, 0.90077335, 0.54488147, 0.62193085,
        0.38807626, 0.48939937, 0.935219  , 0.60035485, 0.88317273,
        0.73216711, 0.29755535, 0.67654747, 0.04812882, 0.68090822,
        0.5420188 , 0.5480054 , 0.95512734, 0.97471169, 0.15487518,
        0.10842618, 0.22118335, 0.05780146, 0.83563523, 0.18728424,
        0.27444001, 0.91975364, 0.89117652, 0.5262705 , 0.84891004,
        0.192538  , 0.77970622, 0.31471084, 0.11993691, 0.87281803,
        0.395529  , 0.92102977, 0.99547516, 0.56230939, 0.33124808,
        0.20684087, 0.41927536, 0.35343746, 0.06611581, 0.06283178]]), [1])


(array([[0.69671163, 0.37938135, 0.01962877, 0.41216136, 0.37148173,
         0.97788283, 0.02499129, 0.6005889 , 0.14764337, 0.8424088 ,
         0.16040903, 0.39975538, 0.92898106, 0.19779657, 0.87747786,
         0.74337398, 0.63857007, 0.80272044, 0.650271  , 0.09690072,
         0.50361457, 0.85529208, 0.44569678, 0.30549416, 0.71785339,
         0.72304234, 0.40479995, 0.21416901, 0.10858433, 0.79087011,
         0.79678342, 0.23938145, 0.11359358, 0.54559259, 0.13060589,
         0.98804945, 0.97202414, 0.90080455, 0.16478893, 0.2052706 ,
         0.07486275, 0.2122904 , 0.26364601, 0.56276843, 0.81800329,
         0.68333503, 0.775529  , 0.30526872, 0.42585386, 0.31985272]]),
 [1])