In [11]:
%load_ext autoreload
%autoreload 2
import numpy as np
from crossover import crossover
from numba import jit
from mfea.amfea import AMFEA
from task.task import DummyTask

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
np.random.seed(0)

In [143]:
l = 3
n = 500
i1 = np.random.randint(-10, 10, size=(n, l))
i2 = np.random.randint(-10, 10, size=(n, l))
rmp = np.random.uniform(size=n)
x = crossover.ArithmeticCrossover()


In [153]:
%timeit -n 100 u = x(rmp, i1, i2)

79.8 µs ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
x = np.random.randint(-4, 4, size=(3, 3))

In [8]:
x

array([[ 0,  3,  1],
       [-4, -1, -1],
       [-1,  3, -3]], dtype=int32)

In [9]:
np.sum(x, axis=1)

array([ 4, -6, -1])

In [20]:
test_task = DummyTask()
test_task.fitness(x)

array([ 4, -6, -1])

In [ ]:
amfea = AMFEA(5, 5, 10, [test_task], crossover.ArithmeticCrossover)

1
0
[[ 7.60595206 -3.72615215  9.14901711 -0.56496858  4.23167634]
 [-6.9261139   4.60884353  2.92528875 -5.70238526 -6.27083561]
 [ 6.15160538  4.9415894   3.49694692 -4.46212498 -6.50182251]
 [ 4.08948517 -0.736996    6.80857065 -5.90268476 -6.70082264]
 [-7.50333885  4.44161325 -9.3909407   4.9398848  -8.1480767 ]]
[ 16.69552478 -11.3652025    3.6261942   -2.44244758 -15.6608582 ]
