In [33]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
cec2017_tasks = get_10_tasks()

In [37]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))

In [26]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [2]:
np.random.seed(0)

In [19]:
mutation = PolynomialMutation(5, 0.1)
crossover = SBXCrossover(mutation)

In [20]:
p1 = np.random.uniform(size=(10, 5))
p2 = np.random.uniform(size=(10, 5))
p1_skill_factor = np.random.randint(0, 10, size=10)
p2_skill_factor = np.random.randint(0, 10, size=10)
rmp = np.full(10, 0.3)
print(crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor))

(array([[0.48907732, 0.21755999, 0.38282867, 0.24502553, 0.38761506],
       [0.25702345, 0.51651566, 0.41216283, 0.62994366, 0.30246677],
       [0.29330261, 0.16726568, 0.96330419, 0.49164913, 0.58479895],
       [0.93257398, 0.79978351, 0.51145685, 0.04501065, 0.27360551],
       [0.91755921, 0.2466678 , 0.16830929, 0.85676823, 0.67986795],
       [0.33830493, 0.37590454, 0.29916411, 0.22162368, 0.54668233],
       [0.26543292, 0.67768779, 0.0042077 , 0.06198635, 0.66880384],
       [0.20565835, 0.10719216, 0.33144878, 0.52079129, 0.97023498],
       [0.9152389 , 0.        , 0.31353523, 0.52489001, 0.98670348],
       [0.71376043, 0.86902526, 0.53801804, 0.2645594 , 0.39786925],
       [0.7984426 , 0.4955613 , 0.82089615, 0.97791707, 0.58542042],
       [0.52776594, 0.69569761, 0.57516585, 0.94148554, 0.23392645],
       [0.36224576, 0.56844494, 0.77220572, 0.59651301, 0.23630839],
       [0.02502096, 0.91025351, 0.26328723, 0.43930677, 0.20838595],
       [0.87963117, 0.16182006, 0

In [39]:
num_indis_per_task = 100
indi_len = 30
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, gnbg_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 65026.655883979685
Mean Fitness: 173836.13839391872

Task 1:
Best Fitness: -701.3558613102514
Mean Fitness: -701.3067565493777

Task 2:
Best Fitness: 43565610040.70057
Mean Fitness: 92497802201.73515

Task 3:
Best Fitness: 494268.3626899761
Mean Fitness: 905392.8543643093

Task 4:
Best Fitness: -334.1558493846376
Mean Fitness: -333.9955164514848



In [40]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 1000
Task 0, Best: 63274.89453125, Avg: 127928.16670243123
Task 1, Best: -701.3966064453125, Avg: -701.3309232677599
Task 2, Best: 43565608960.0, Avg: 68497121021.8612
Task 3, Best: 477495.0, Avg: 638126.3093685278
Task 4, Best: -334.1809997558594, Avg: -334.04843239974207
Time taken each gen: 0.0989 seconds

Gen 100
Evaluation count: 101000
Task 0, Best: -134.52935791015625, Avg: 71.55827896595001
Task 1, Best: -701.6751098632812, Avg: -701.666303100586
Task 2, Best: 1583486848.0, Avg: 1692922316.8
Task 3, Best: 11083.0185546875, Avg: 12742.030595703125
Task 4, Best: -334.6695251464844, Avg: -334.65916412353516
Time taken each gen: 0.1076 seconds

Gen 200
Evaluation count: 201000
Task 0, Best: -1036.635986328125, Avg: -1032.867802734375
Task 1, Best: -701.8646850585938, Avg: -701.8594567871094
Task 2, Best: 60411824.0, Avg: 66400893.12
Task 3, Best: 1033.4742431640625, Avg: 1093.8527368164061
Task 4, Best: -334.9659423828125, Avg: -334.9602331542969
Time taken 

In [ ]:
print(amfea.eval_cnt)

2182358


In [ ]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.92707397e-01 9.28115568e-01 1.95030332e-01 9.19464883e-01
 7.00052070e-01 1.94086735e-01 9.32649332e-01 2.01325155e-01
 3.79375448e-01 6.99848299e-01 1.94312757e-01 1.91218354e-01
 9.32632332e-01 7.04786795e-01 1.85863576e-01 2.03263489e-01
 6.95277561e-01 9.17992806e-01 9.40317772e-01 9.22242633e-01
 7.15224694e-01 2.01667188e-01 7.00697586e-01 1.83446501e-01
 7.04126343e-01 1.93066440e-01 7.03597835e-01 9.20387664e-01
 7.05086955e-01 7.20233286e-04 7.07544023e-01 9.28164487e-01
 1.85552661e-01 1.80195522e-01 2.14168065e-01 1.89942223e-01
 7.02260894e-01 7.04083201e-01 9.23887402e-01 3.15534153e-03
 9.19865290e-01 7.02337478e-01 9.06982242e-01 9.22580845e-01
 6.97567082e-01 7.06233374e-01 7.08674613e-01 1.98085688e-01
 9.28875413e-01 1.99998422e-01]
[6637.95167233]


In [ ]:
print(np.max(amfea.pop))

0.9795161081006124


In [ ]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [ ]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([22735.02372398])

In [ ]:
print(x_test)

[0.37138179 0.73449412 0.36311813 0.78244749 0.99178212 0.47985734
 0.36771698 0.51114184 0.04594897 0.84181967 0.61995408 0.63615412
 0.46263011 0.8640062  0.14332885 0.62474759 0.54728951 0.59178973
 0.36934856 0.98753811 0.03777077 0.29882631 0.96237095 0.15249977
 0.7886243  0.27673331 0.88030284 0.30618377 0.50073916 0.18406873
 0.35633323 0.47317796 0.91791397 0.80261628 0.74382469 0.86932051
 0.35167865 0.03108078 0.88207472 0.64581258 0.17599662 0.44207642
 0.74174619 0.14262801 0.26605845 0.89521602 0.44415947 0.62751617
 0.62814485 0.30749574]


In [ ]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[152104.57279382]
[425081.00403927]
[519128.14154837]
[53.38544507]
[5.70541367e+09]
[21.72861174]
[104.8360553]
[21254.0220888]
[124.49564953]
[113062.82998873]


In [ ]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [ ]:
t = np.arange(10)

In [ ]:
t = np.array([t, t])
t

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
t[:, :3]

array([[0, 1, 2],
       [0, 1, 2]])