In [ ]:
%load_ext autoreload
%autoreload 2
import numpy as np
from crossover import crossover
from numba import jit
from mfea.amfea import AMFEA
from task.task import DummyTask
from mutation.mutation import AbstractMutation, RandomMutation, AdditiveMutation

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [43]:
np.random.seed(0)

In [143]:
l = 3
n = 500
i1 = np.random.randint(-10, 10, size=(n, l))
i2 = np.random.randint(-10, 10, size=(n, l))
rmp = np.random.uniform(size=n)
x = crossover.ArithmeticCrossover()


In [153]:
%timeit -n 100 u = x(rmp, i1, i2)

79.8 µs ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
x = np.random.randint(-4, 4, size=(3, 3))

In [8]:
x

array([[ 0,  3,  1],
       [-4, -1, -1],
       [-1,  3, -3]], dtype=int32)

In [9]:
np.sum(x, axis=1)

array([ 4, -6, -1])

In [20]:
test_task = DummyTask()
test_task.fitness(x)

array([ 4, -6, -1])

In [32]:
amfea = AMFEA(5, 5, 10, [test_task], crossover.ArithmeticCrossover)

1
0


In [33]:
amfea.pop

array([[-5.65099015,  4.98508834,  4.63387513, -9.08770726, -5.81685941],
       [-4.26169913,  3.54526611, -8.73923421,  1.11298486, -9.81519853],
       [ 6.66076195,  9.68658869,  4.06989568, -6.36737599,  0.24786927],
       [ 1.60894274,  5.75084312,  2.1295092 , -5.6319429 , -0.8966237 ],
       [ 7.57739484, -0.15463517,  4.31122315, -0.27680879,  4.170963  ]])

In [44]:
rm = AdditiveMutation(100, 1)
t = np.random.uniform(-100, 100, size=(5, 5))
print(t)
print(rm(t))

NameError: name 'AdditiveMutation' is not defined