In [64]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [79]:
cec2017_tasks = get_10_tasks()

In [66]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))

In [67]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [80]:
np.random.seed(0)

In [98]:
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation)

In [70]:
def rmp_matrix_to_array(rmp_matrix, p1_skill_factor, p2_skill_factor):
    return rmp_matrix[p1_skill_factor, p2_skill_factor]

In [82]:
print(len(cec2017_tasks))

10


In [108]:
p1 = np.random.uniform(size=(10, 50))
p2 = np.random.uniform(size=(10, 50))
p1_skill_factor = np.random.randint(0, 2, size=10)
p2_skill_factor = np.random.randint(0, 2, size=10)
p1_fitness = np.random.uniform(size=10)
p2_fitness = np.random.uniform(size=10)
rmp = np.full(shape=(2, 2), fill_value=0.3)
off, off_skill_factor, off_fitness = crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor, p1_fitness, p2_fitness, cec2017_tasks, eval=False)

In [109]:
print(np.max(off))

1.0


In [110]:
rmp_matrix_to_array(rmp, p1_skill_factor, p2_skill_factor)

array([0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3])

In [111]:
num_indis_per_task = 50
indi_len = 50
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation, eta=2)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 119842.55426057834
Mean Fitness: 166914.40365790948

Task 1:
Best Fitness: 286232.7192528038
Mean Fitness: 479307.9406127449

Task 2:
Best Fitness: 283083.5698670431
Mean Fitness: 496826.4379942231

Task 3:
Best Fitness: 42.39640202260273
Mean Fitness: 50.16789220889359

Task 4:
Best Fitness: 3999747949.703829
Mean Fitness: 6252286973.801757

Task 5:
Best Fitness: 21.52808381676207
Mean Fitness: 21.72840820145346

Task 6:
Best Fitness: 79.66764684732715
Mean Fitness: 100.24664040966618

Task 7:
Best Fitness: 17240.220948277405
Mean Fitness: 20636.451886385476

Task 8:
Best Fitness: 82.03549955086858
Mean Fitness: 124.88187583003565

Task 9:
Best Fitness: 83574.14871569995
Mean Fitness: 123224.37864086946



In [ ]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 0
Task 0, Best: 113526.77820368408, Avg: 142386.16687863832
Task 1, Best: 301545.9860046316, Avg: 404260.462538067
Task 2, Best: 367644.6961715585, Avg: 432549.4961056955
Task 3, Best: 38.22277568263915, Avg: 45.3887449915617
Task 4, Best: 2055919034.3642907, Avg: 4366987481.996906
Task 5, Best: 21.49657955037943, Avg: 21.63475456187017
Task 6, Best: 85.59006484135281, Avg: 93.98963357426595
Task 7, Best: 16530.459241479053, Avg: 19172.95885243127
Task 8, Best: 83.30767653656936, Avg: 107.74565319304203
Task 9, Best: 82229.1042864103, Avg: 106180.97253099621
Time taken each gen: 0.1291 seconds



In [90]:
print(np.max(amfea.pop))

0.9999784003327589


In [ ]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [ ]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([19624.00486413])

In [ ]:
print(x_test)

[0.18541045 0.10918362 0.41620666 0.05202045 0.73581345 0.10242111
 0.27975593 0.500361   0.28994784 0.69074022 0.43137988 0.69181414
 0.18295413 0.60222251 0.94836878 0.83444372 0.74597701 0.29911743
 0.86886052 0.66123358 0.01325606 0.14413201 0.93982458 0.31279125
 0.83371066 0.9945565  0.37324847 0.94440294 0.76597573 0.93927236
 0.73464583 0.73928831 0.24930223 0.86097878 0.48044106 0.70032713
 0.18992072 0.18732098 0.34944063 0.67636843 0.45803565 0.81829454
 0.77605716 0.66082975 0.67077776 0.39174871 0.01667886 0.62422151
 0.90594216 0.4268725 ]


In [ ]:
super_tasks = get_2_tasks(1)
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

NameError: name 'get_2_tasks' is not defined

In [ ]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [ ]:
#test 
p = np.array([1, 2, 3])
def f(p):
    p += 3
f(p)
print(p)

[4 5 6]
