In [64]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [79]:
cec2017_tasks = get_10_tasks()

In [66]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))

In [67]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [80]:
np.random.seed(0)

In [98]:
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation)

In [70]:
def rmp_matrix_to_array(rmp_matrix, p1_skill_factor, p2_skill_factor):
    return rmp_matrix[p1_skill_factor, p2_skill_factor]

In [82]:
print(len(cec2017_tasks))

10


In [108]:
p1 = np.random.uniform(size=(10, 50))
p2 = np.random.uniform(size=(10, 50))
p1_skill_factor = np.random.randint(0, 2, size=10)
p2_skill_factor = np.random.randint(0, 2, size=10)
p1_fitness = np.random.uniform(size=10)
p2_fitness = np.random.uniform(size=10)
rmp = np.full(shape=(2, 2), fill_value=0.3)
off, off_skill_factor, off_fitness = crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor, p1_fitness, p2_fitness, cec2017_tasks, eval=False)

In [109]:
print(np.max(off))

1.0


In [110]:
rmp_matrix_to_array(rmp, p1_skill_factor, p2_skill_factor)

array([0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3])

In [ ]:
num_indis_per_task = 100
indi_len = 50
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation, eta=2)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 119942.44515243385
Mean Fitness: 165559.68141275048

Task 1:
Best Fitness: 361858.9083699929
Mean Fitness: 480119.2297387419

Task 2:
Best Fitness: 308605.1606399592
Mean Fitness: 489377.1078875712

Task 3:
Best Fitness: 40.93402821240308
Mean Fitness: 50.70281108619733

Task 4:
Best Fitness: 3290258454.6844053
Mean Fitness: 6222720432.233082

Task 5:
Best Fitness: 21.457730213775395
Mean Fitness: 21.711551975861397

Task 6:
Best Fitness: 86.4547190995287
Mean Fitness: 100.6735587657009

Task 7:
Best Fitness: 18963.22398104165
Mean Fitness: 21073.755865436626

Task 8:
Best Fitness: 79.99567052202349
Mean Fitness: 125.20263270152404

Task 9:
Best Fitness: 86021.29725785153
Mean Fitness: 121718.66420500605



In [114]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 0
Task 0, Best: 72975.78705186633, Avg: 134060.82966121982
Task 1, Best: 309718.1825671343, Avg: 407540.73577611806
Task 2, Best: 288526.6758626887, Avg: 408707.09219814464
Task 3, Best: 38.11744553660621, Avg: 45.024343735088905
Task 4, Best: 2426943937.601818, Avg: 4716878220.009815
Task 5, Best: 20.538638780216573, Avg: 21.560461408295918
Task 6, Best: 65.93947344587036, Avg: 90.59339397188242
Task 7, Best: 17144.08246936057, Avg: 19755.24900990665
Task 8, Best: 72.42147550907163, Avg: 101.8750554157855
Task 9, Best: 80732.0871645476, Avg: 100897.21753906706
Time taken each gen: 0.1927 seconds

Gen 100
Evaluation count: 0
Task 0, Best: 1080.0344148221316, Avg: 1247.113332832825
Task 1, Best: 12068.237190366426, Avg: 26429.54363976254
Task 2, Best: 13048.562929880727, Avg: 16056.846084254634
Task 3, Best: 9.905007202303686, Avg: 11.063734488252763
Task 4, Best: 379627.68949093006, Avg: 474596.8018127775
Task 5, Best: 17.859107806454695, Avg: 19.777601940560494

In [90]:
print(np.max(amfea.pop))

0.9999784003327589


In [ ]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [ ]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([19624.00486413])

In [ ]:
print(x_test)

[0.18541045 0.10918362 0.41620666 0.05202045 0.73581345 0.10242111
 0.27975593 0.500361   0.28994784 0.69074022 0.43137988 0.69181414
 0.18295413 0.60222251 0.94836878 0.83444372 0.74597701 0.29911743
 0.86886052 0.66123358 0.01325606 0.14413201 0.93982458 0.31279125
 0.83371066 0.9945565  0.37324847 0.94440294 0.76597573 0.93927236
 0.73464583 0.73928831 0.24930223 0.86097878 0.48044106 0.70032713
 0.18992072 0.18732098 0.34944063 0.67636843 0.45803565 0.81829454
 0.77605716 0.66082975 0.67077776 0.39174871 0.01667886 0.62422151
 0.90594216 0.4268725 ]


In [ ]:
super_tasks = get_2_tasks(1)
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

NameError: name 'get_2_tasks' is not defined

In [ ]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [ ]:
#test 
p = np.array([1, 2, 3])
def f(p):
    p += 3
f(p)
print(p)

[4 5 6]
