In [46]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))
gnbg_tasks.append(GNBGTask(6, 100))

In [47]:
cec2017_tasks = get_10_tasks()

In [42]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [51]:
num_indis_per_task = 100
indi_len = 50
crossover = BLXCrossover()
mutation = PolynomialMutation(15)
rmp = NormalRMP(0.4)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 113291.44275684243
Mean Fitness: 166005.8696397565

Task 1:
Best Fitness: 337202.6133461816
Mean Fitness: 492136.161562573

Task 2:
Best Fitness: 303978.0288174722
Mean Fitness: 487835.1155910769

Task 3:
Best Fitness: 37.097844388084994
Mean Fitness: 49.630184032860456

Task 4:
Best Fitness: 3557321321.044695
Mean Fitness: 6107443983.606149

Task 5:
Best Fitness: 21.464106194453787
Mean Fitness: 21.7239995113881

Task 6:
Best Fitness: 86.80630487035613
Mean Fitness: 100.52547258987475

Task 7:
Best Fitness: 17386.816064023587
Mean Fitness: 20821.023205730682

Task 8:
Best Fitness: 87.93812085817802
Mean Fitness: 122.06000734263316

Task 9:
Best Fitness: 86766.3814281801
Mean Fitness: 121411.39842615809



In [ ]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=500)

Gen 0
Evaluation count: 368
Task 0, Best: 105858.8515625, Avg: 151073.03095688557
Task 1, Best: 337202.6133461816, Avg: 454994.1753051512
Task 2, Best: 303978.0288174722, Avg: 453633.1909742496
Task 3, Best: 37.097844388084994, Avg: 48.101607907401124
Task 4, Best: 2562591488.0, Avg: 5161820984.590952
Task 5, Best: 21.464106194453787, Avg: 21.68744516937303
Task 6, Best: 86.80630487035613, Avg: 98.92804222121815
Task 7, Best: 17386.816064023587, Avg: 20289.479052308187
Task 8, Best: 79.92616271972656, Avg: 113.73743999801485
Task 9, Best: 86766.3814281801, Avg: 112533.07499518314
Time taken each gen: 0.0322 seconds

Gen 500
Evaluation count: 220503
Task 0, Best: 843.1220703125, Avg: 1439.6223345947265
Task 1, Best: 258.85906982421875, Avg: 364.9025203909264
Task 2, Best: 496.1340026855469, Avg: 662.9388384420522
Task 3, Best: 5.321499697907235, Avg: 6.055285425928883
Task 4, Best: 429094.3125, Avg: 896011.5775
Task 5, Best: 5.547190189361572, Avg: 6.289280296620929
Task 6, Best: 16.841

In [53]:
print(amfea.eval_cnt)

2182358


In [28]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.92707397e-01 9.28115568e-01 1.95030332e-01 9.19464883e-01
 7.00052070e-01 1.94086735e-01 9.32649332e-01 2.01325155e-01
 3.79375448e-01 6.99848299e-01 1.94312757e-01 1.91218354e-01
 9.32632332e-01 7.04786795e-01 1.85863576e-01 2.03263489e-01
 6.95277561e-01 9.17992806e-01 9.40317772e-01 9.22242633e-01
 7.15224694e-01 2.01667188e-01 7.00697586e-01 1.83446501e-01
 7.04126343e-01 1.93066440e-01 7.03597835e-01 9.20387664e-01
 7.05086955e-01 7.20233286e-04 7.07544023e-01 9.28164487e-01
 1.85552661e-01 1.80195522e-01 2.14168065e-01 1.89942223e-01
 7.02260894e-01 7.04083201e-01 9.23887402e-01 3.15534153e-03
 9.19865290e-01 7.02337478e-01 9.06982242e-01 9.22580845e-01
 6.97567082e-01 7.06233374e-01 7.08674613e-01 1.98085688e-01
 9.28875413e-01 1.99998422e-01]
[6637.95167233]


In [31]:
print(np.max(amfea.pop))

0.9795161081006124


In [7]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [9]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([22735.02372398])

In [199]:
print(x_test)

[0.37138179 0.73449412 0.36311813 0.78244749 0.99178212 0.47985734
 0.36771698 0.51114184 0.04594897 0.84181967 0.61995408 0.63615412
 0.46263011 0.8640062  0.14332885 0.62474759 0.54728951 0.59178973
 0.36934856 0.98753811 0.03777077 0.29882631 0.96237095 0.15249977
 0.7886243  0.27673331 0.88030284 0.30618377 0.50073916 0.18406873
 0.35633323 0.47317796 0.91791397 0.80261628 0.74382469 0.86932051
 0.35167865 0.03108078 0.88207472 0.64581258 0.17599662 0.44207642
 0.74174619 0.14262801 0.26605845 0.89521602 0.44415947 0.62751617
 0.62814485 0.30749574]


In [200]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[152104.57279382]
[425081.00403927]
[519128.14154837]
[53.38544507]
[5.70541367e+09]
[21.72861174]
[104.8360553]
[21254.0220888]
[124.49564953]
[113062.82998873]


In [201]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [109]:
t = np.arange(10)

In [110]:
t = np.array([t, t])
t

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [111]:
t[:, :3]

array([[0, 1, 2],
       [0, 1, 2]])