In [36]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [37]:
cec2017_tasks = get_10_tasks()

In [42]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))

In [26]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [38]:
mutation = PolynomialMutation(15)
crossover = SBXCrossover(mutation)

In [39]:
p1 = np.random.uniform(size=(10, 5))
p2 = np.random.uniform(size=(10, 5))
p1_skill_factor = np.random.randint(0, 10, size=10)
p2_skill_factor = np.random.randint(0, 10, size=10)
rmp = np.full(10, 0.3)
print(crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor))

(array([[0.        , 0.51276432, 0.88197055, 0.24723801, 0.18028401],
       [0.0737507 , 0.78589334, 0.44599093, 0.78751129, 0.26795082],
       [0.04202596, 0.94727554, 0.93627634, 0.14395271, 0.29634934],
       [0.62658671, 0.83730384, 0.20189697, 0.92909158, 0.43043313],
       [0.87261904, 0.57262614, 0.03063418, 0.07006596, 0.65107592],
       [0.78749846, 0.94316766, 0.22407618, 0.01718698, 0.85578098],
       [0.20966941, 0.74705581, 0.72994186, 0.96051828, 0.83527911],
       [0.68804182, 0.31789978, 0.43546863, 0.64913384, 0.86839733],
       [0.98077614, 0.28965293, 0.41954523, 0.61896468, 0.07129857],
       [0.08833873, 0.2692328 , 0.38850655, 0.61428178, 0.83954932],
       [0.86743762, 0.10702949, 0.67131258, 0.96436617, 0.334611  ],
       [0.56291856, 0.72653526, 0.50888124, 0.13144656, 0.53663237],
       [0.65743806, 0.06999427, 0.16150156, 0.68895345, 0.90498998],
       [0.4321365 , 0.09844241, 0.52283145, 0.56488945, 0.33877578],
       [0.01392454, 0.82782053, 0

In [43]:
num_indis_per_task = 100
indi_len = 30
mutation = PolynomialMutation(15)
crossover = SBXCrossover(mutation)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, gnbg_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 85462.0992279296
Mean Fitness: 174328.60699334275

Task 1:
Best Fitness: -701.3636358014778
Mean Fitness: -701.3095289555603

Task 2:
Best Fitness: 38458597907.03809
Mean Fitness: 89658319678.8632

Task 3:
Best Fitness: 447895.51213533396
Mean Fitness: 906256.4991710217



In [44]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 748
Task 0, Best: 82291.8046875, Avg: 136010.1082189341
Task 1, Best: -701.378662109375, Avg: -701.3357015253988
Task 2, Best: 35232444416.0, Avg: 66113888368.0771
Task 3, Best: 355427.0625, Avg: 692357.7048256178
Time taken each gen: 0.0832 seconds

Gen 100
Evaluation count: 76794
Task 0, Best: -639.7749633789062, Avg: -588.2769848632812
Task 1, Best: -701.7703857421875, Avg: -701.7629614257812
Task 2, Best: 250042768.0, Avg: 335312572.32
Task 3, Best: 6498.986328125, Avg: 7967.543608398438
Time taken each gen: 0.0785 seconds

Gen 200
Evaluation count: 152206
Task 0, Best: -890.2080688476562, Avg: -890.1141058349609
Task 1, Best: -701.7785034179688, Avg: -701.778466796875
Task 2, Best: 132803320.0, Avg: 132941529.92
Task 3, Best: 2895.30322265625, Avg: 3186.8062255859377
Time taken each gen: 0.0938 seconds

Gen 300
Evaluation count: 227754
Task 0, Best: -890.7199096679688, Avg: -890.7167205810547
Task 1, Best: -701.7951049804688, Avg: -701.7942333984375
Task 2,

In [ ]:
print(amfea.eval_cnt)

2182358


In [ ]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.92707397e-01 9.28115568e-01 1.95030332e-01 9.19464883e-01
 7.00052070e-01 1.94086735e-01 9.32649332e-01 2.01325155e-01
 3.79375448e-01 6.99848299e-01 1.94312757e-01 1.91218354e-01
 9.32632332e-01 7.04786795e-01 1.85863576e-01 2.03263489e-01
 6.95277561e-01 9.17992806e-01 9.40317772e-01 9.22242633e-01
 7.15224694e-01 2.01667188e-01 7.00697586e-01 1.83446501e-01
 7.04126343e-01 1.93066440e-01 7.03597835e-01 9.20387664e-01
 7.05086955e-01 7.20233286e-04 7.07544023e-01 9.28164487e-01
 1.85552661e-01 1.80195522e-01 2.14168065e-01 1.89942223e-01
 7.02260894e-01 7.04083201e-01 9.23887402e-01 3.15534153e-03
 9.19865290e-01 7.02337478e-01 9.06982242e-01 9.22580845e-01
 6.97567082e-01 7.06233374e-01 7.08674613e-01 1.98085688e-01
 9.28875413e-01 1.99998422e-01]
[6637.95167233]


In [ ]:
print(np.max(amfea.pop))

0.9795161081006124


In [ ]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [ ]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([22735.02372398])

In [ ]:
print(x_test)

[0.37138179 0.73449412 0.36311813 0.78244749 0.99178212 0.47985734
 0.36771698 0.51114184 0.04594897 0.84181967 0.61995408 0.63615412
 0.46263011 0.8640062  0.14332885 0.62474759 0.54728951 0.59178973
 0.36934856 0.98753811 0.03777077 0.29882631 0.96237095 0.15249977
 0.7886243  0.27673331 0.88030284 0.30618377 0.50073916 0.18406873
 0.35633323 0.47317796 0.91791397 0.80261628 0.74382469 0.86932051
 0.35167865 0.03108078 0.88207472 0.64581258 0.17599662 0.44207642
 0.74174619 0.14262801 0.26605845 0.89521602 0.44415947 0.62751617
 0.62814485 0.30749574]


In [ ]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[152104.57279382]
[425081.00403927]
[519128.14154837]
[53.38544507]
[5.70541367e+09]
[21.72861174]
[104.8360553]
[21254.0220888]
[124.49564953]
[113062.82998873]


In [ ]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [ ]:
t = np.arange(10)

In [ ]:
t = np.array([t, t])
t

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
t[:, :3]

array([[0, 1, 2],
       [0, 1, 2]])