In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

In [12]:
cec2017_tasks = get_2_tasks(0)

In [37]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))

In [26]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [11]:
np.random.seed(0)

In [8]:
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation)

In [14]:
p1 = np.random.uniform(size=(10, 5))
p2 = np.random.uniform(size=(10, 5))
p1_skill_factor = np.random.randint(0, 10, size=10)
p2_skill_factor = np.random.randint(0, 10, size=10)
rmp = np.full(10, 0.3)
print(crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor))

(array([[0.69541079, 0.95756825, 0.83488547, 0.69847786, 0.        ],
       [0.53798364, 0.35148311, 0.96450357, 0.72967205, 0.44820518],
       [0.13469588, 0.41308345, 0.48897307, 0.        , 0.22359936],
       [0.64170121, 0.42294978, 1.        , 0.12127821, 0.00746291],
       [0.85985949, 0.72126437, 0.76493689, 0.38792101, 0.74370146],
       [0.03441911, 0.57420217, 0.85300536, 0.04696314, 0.3899212 ],
       [0.89007254, 0.80445126, 0.19100558, 0.27273255, 0.66511406],
       [0.90239944, 0.51089071, 0.02799495, 0.54215864, 0.04294205],
       [0.39217296, 0.04115659, 0.92330057, 0.40623497, 0.94428218],
       [0.83881577, 0.6928224 , 0.95799151, 0.14222247, 0.08777354],
       [0.2453717 , 0.38102144, 0.42403833, 0.26753056, 0.11264625],
       [0.13867957, 0.68820216, 0.95588973, 0.34485436, 0.14278639],
       [0.2600578 , 0.15217505, 0.19473966, 0.66216051, 0.38492733],
       [0.25045429, 0.58115791, 0.89782395, 0.02442901, 0.59671877],
       [0.84029349, 0.39577765, 0

In [23]:
num_indis_per_task = 50
indi_len = 50
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation, eta=2)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 27.433700304241754
Mean Fitness: 42.25238837435661

Task 1:
Best Fitness: 29497.87851032304
Mean Fitness: 40987.29310782642



In [24]:
bfs, mfs = amfea.fit(max_eval=100000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 200
Task 0, Best: 16.61356544494629, Avg: 33.35090678332586
Task 1, Best: 21933.80859375, Avg: 32455.50353262065
Time taken each gen: 0.0091 seconds

Gen 100
Evaluation count: 20200
Task 0, Best: 1.2715215682983398, Avg: 1.2920649123191834
Task 1, Best: 663.4100341796875, Avg: 682.8722680664063
Time taken each gen: 0.0074 seconds

Gen 200
Evaluation count: 40200
Task 0, Best: 1.062530517578125, Avg: 1.0633087515830995
Task 1, Best: 392.6062927246094, Avg: 398.0374188232422
Time taken each gen: 0.0100 seconds

Gen 300
Evaluation count: 60200
Task 0, Best: 0.7802925109863281, Avg: 0.7845035481452942
Task 1, Best: 296.0069885253906, Avg: 299.34739196777343
Time taken each gen: 0.0084 seconds

Gen 400
Evaluation count: 80200
Task 0, Best: 0.5109701156616211, Avg: 0.5127342367172241
Task 1, Best: 255.78981018066406, Avg: 256.6700509643555
Time taken each gen: 0.0107 seconds

Out of evaluation!
Task 0, Best: 0.3488507866859436, Avg: 0.35202028930187224
Task 1, Best: 2

In [17]:
print(amfea.eval_cnt)

100000


In [ ]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.92707397e-01 9.28115568e-01 1.95030332e-01 9.19464883e-01
 7.00052070e-01 1.94086735e-01 9.32649332e-01 2.01325155e-01
 3.79375448e-01 6.99848299e-01 1.94312757e-01 1.91218354e-01
 9.32632332e-01 7.04786795e-01 1.85863576e-01 2.03263489e-01
 6.95277561e-01 9.17992806e-01 9.40317772e-01 9.22242633e-01
 7.15224694e-01 2.01667188e-01 7.00697586e-01 1.83446501e-01
 7.04126343e-01 1.93066440e-01 7.03597835e-01 9.20387664e-01
 7.05086955e-01 7.20233286e-04 7.07544023e-01 9.28164487e-01
 1.85552661e-01 1.80195522e-01 2.14168065e-01 1.89942223e-01
 7.02260894e-01 7.04083201e-01 9.23887402e-01 3.15534153e-03
 9.19865290e-01 7.02337478e-01 9.06982242e-01 9.22580845e-01
 6.97567082e-01 7.06233374e-01 7.08674613e-01 1.98085688e-01
 9.28875413e-01 1.99998422e-01]
[6637.95167233]


In [ ]:
print(np.max(amfea.pop))

0.9795161081006124


In [22]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [23]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([19624.00486413])

In [24]:
print(x_test)

[0.18541045 0.10918362 0.41620666 0.05202045 0.73581345 0.10242111
 0.27975593 0.500361   0.28994784 0.69074022 0.43137988 0.69181414
 0.18295413 0.60222251 0.94836878 0.83444372 0.74597701 0.29911743
 0.86886052 0.66123358 0.01325606 0.14413201 0.93982458 0.31279125
 0.83371066 0.9945565  0.37324847 0.94440294 0.76597573 0.93927236
 0.73464583 0.73928831 0.24930223 0.86097878 0.48044106 0.70032713
 0.18992072 0.18732098 0.34944063 0.67636843 0.45803565 0.81829454
 0.77605716 0.66082975 0.67077776 0.39174871 0.01667886 0.62422151
 0.90594216 0.4268725 ]


In [1]:
super_tasks = get_2_tasks(1)
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

NameError: name 'get_2_tasks' is not defined

In [27]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [25]:
#test 
p = np.array([1, 2, 3])
def f(p):
    p += 3
f(p)
print(p)

[4 5 6]
