In [4]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))

In [6]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [7]:
np.random.seed(0)

In [8]:
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation)

In [9]:
def rmp_matrix_to_array(rmp_matrix, p1_skill_factor, p2_skill_factor):
    return rmp_matrix[p1_skill_factor, p2_skill_factor]

In [10]:
cec2017_tasks = get_2_tasks(5)


PI_L


In [11]:
print(len(cec2017_tasks))

2


In [28]:
p1 = np.random.uniform(size=(10, 50))
p2 = np.random.uniform(size=(10, 50))
p1_skill_factor = np.random.randint(0, 2, size=10)
p2_skill_factor = np.random.randint(0, 2, size=10)
p1_fitness = np.random.uniform(size=10)
p2_fitness = np.random.uniform(size=10)
rmp = np.full(shape=(2, 2), fill_value=0.3)
off, off_skill_factor, off_fitness = crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor, p1_fitness, p2_fitness, cec2017_tasks, eval=False)

In [29]:
num_indis_per_task = 100
indi_len = 50
mutation = PolynomialMutation(5, 0.02)
crossover = SBXCrossover(mutation, eta=2)
# crossover = BLXCrossover()
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task,
              indi_len,
              cec2017_tasks,
              crossover,
              mutation,
              rmp)

Initialization:
Task 0:
Best Fitness: 31087.682014678012
Mean Fitness: 42356.708447059005

Task 1:
Best Fitness: 107065.61500623611
Mean Fitness: 177435.8641183864



In [30]:
bfs, mfs = amfea.fit(num_gen=1000, monitor=True, monitor_rate=100)

Gen 0
Evaluation count: 0
Task 0, Best: 21063.674152758187, Avg: 33789.78584094434
Task 1, Best: 72552.05231130493, Avg: 138904.1274622957
Time taken each gen: 0.0060 seconds

Gen 100
Evaluation count: 0
Task 0, Best: 1513.3876244332848, Avg: 1517.8143574599824
Task 1, Best: 2152.624826615446, Avg: 2379.5360983734868
Time taken each gen: 0.0323 seconds

Gen 200
Evaluation count: 0
Task 0, Best: 1462.6638060773855, Avg: 1466.1415689046655
Task 1, Best: 521.7755590364667, Avg: 543.563642554824
Time taken each gen: 0.0335 seconds

Gen 300
Evaluation count: 0
Task 0, Best: 1385.2657247148352, Avg: 1385.4131218095235
Task 1, Best: 194.2061063259601, Avg: 202.96018964342173
Time taken each gen: 0.0392 seconds

Gen 400
Evaluation count: 0
Task 0, Best: 1336.637450855934, Avg: 1337.325339999686
Task 1, Best: 73.12867098222813, Avg: 73.87704905131216
Time taken each gen: 0.0337 seconds

Gen 500
Evaluation count: 0
Task 0, Best: 1296.1639200230597, Avg: 1302.4856780698055
Task 1, Best: 36.447714

In [149]:
for task in gnbg_tasks:
    print(task.gnbg.OptimumValue)

-1081.9837994003399
-703.1328146165181
-357.5797495903721
-382.6205211774271
-337.50899809752036


In [90]:
print(np.max(amfea.pop))

0.9999784003327589


In [120]:
dim = 50

In [121]:
x_test = np.random.uniform(0, 1, size=dim)

In [122]:
print(x_test)

[0.85907482 0.94008339 0.50785754 0.72509466 0.06625432 0.66633294
 0.74234832 0.90374985 0.23927356 0.32128177 0.31552997 0.67909715
 0.43332934 0.98120044 0.2745511  0.60376838 0.85184482 0.19065958
 0.6426098  0.40787485 0.20654012 0.13219135 0.41308363 0.54744061
 0.57048436 0.42555876 0.19406744 0.27179178 0.297762   0.11140318
 0.45006828 0.16531338 0.92069788 0.88879073 0.44608596 0.23528611
 0.58133187 0.71235906 0.17826929 0.45866792 0.01148249 0.91859941
 0.35862434 0.36346905 0.90740653 0.8934829  0.99067995 0.27788791
 0.08522302 0.15000237]


In [124]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[165305.05004158]
[500797.26552413]
[469812.83455903]
[52.41419773]
[5.98007733e+09]
[21.6372491]
[96.7504262]
[18339.88464123]
[137.7442226]
[106369.7608199]


In [ ]:
165305.0500415824
500797.2655241336
469812.83455903106
52.41419772668738
5980077333.781868
21.637249102506384
96.75042619986894
18339.884641225744
137.74422260305982
106369.76081990033

In [125]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [39]:
n = 4
dim = 5
p = np.random.uniform(0, 1, size=(n, dim))
skill_factor = np.random.randint(0, 2, size=n)

In [40]:
mean = np.zeros((2, dim))

In [49]:
for task_id in range(2):
    task_mask = skill_factor == task_id
    g = p[task_mask]
    print(g)
    mean[task_id] = np.mean(g, axis=0)
    print(mean[task_id])


[[0.9312767  0.83727121 0.12451126 0.27192389 0.99756742]
 [0.27769765 0.06069361 0.84285459 0.85331673 0.66851232]]
[0.60448718 0.44898241 0.48368293 0.56262031 0.83303987]
[[0.2486302  0.37827109 0.55353126 0.54334964 0.86687774]
 [0.10331157 0.12251464 0.15755651 0.06655269 0.25442498]]
[0.17597088 0.25039286 0.35554388 0.30495116 0.56065136]


In [45]:
var = np.zeros((2, dim))

In [48]:
for task_id in range(2):
    task_mask = skill_factor == task_id
    g = p[task_mask]
    print(g)
    mean[task_id] = np.var(g, axis=0)
    print(mean[task_id])

[[0.9312767  0.83727121 0.12451126 0.27192389 0.99756742]
 [0.27769765 0.06069361 0.84285459 0.85331673 0.66851232]]
[0.10679139 0.15076819 0.12900428 0.08450441 0.02706931]
[[0.2486302  0.37827109 0.55353126 0.54334964 0.86687774]
 [0.10331157 0.12251464 0.15755651 0.06655269 0.25442498]]
[0.00527938 0.01635284 0.039199   0.05683383 0.09377459]


In [23]:
x1 = np.random.randint(5, 10, size=50)
x2 = np.random.randint(1, 5, size=50)

In [24]:
print(x1)
print(x2)

[5 5 7 5 9 8 9 7 9 9 9 5 5 7 5 9 8 7 7 9 7 9 5 9 9 8 7 9 6 5 7 9 8 9 7 7 6
 9 6 5 7 8 6 9 7 5 6 6 9 6]
[1 4 1 2 3 4 1 2 1 2 3 1 2 3 4 1 1 1 2 4 4 2 4 2 2 2 1 1 1 1 3 3 2 3 3 1 4
 3 1 4 2 1 4 3 3 4 3 2 2 4]


In [25]:
diff = x1 - x2
diff_percentage = (diff / x1) * 100
print(diff_percentage)

[80.         20.         85.71428571 60.         66.66666667 50.
 88.88888889 71.42857143 88.88888889 77.77777778 66.66666667 80.
 60.         57.14285714 20.         88.88888889 87.5        85.71428571
 71.42857143 55.55555556 42.85714286 77.77777778 20.         77.77777778
 77.77777778 75.         85.71428571 88.88888889 83.33333333 80.
 57.14285714 66.66666667 75.         66.66666667 57.14285714 85.71428571
 33.33333333 66.66666667 83.33333333 20.         71.42857143 87.5
 33.33333333 66.66666667 57.14285714 20.         50.         66.66666667
 77.77777778 33.33333333]


In [26]:
total_performance_diff = np.sum(diff_percentage)

In [27]:
total_performance_diff / 50

np.float64(64.93809523809524)