In [15]:
%load_ext autoreload
%autoreload 2
import numpy as np
from mutation import *
from crossover import *
from rmp import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
p = np.full((10, 5), 10.0, dtype=np.float32)
skf = np.random.randint(0, 2, 10)
am = AdditiveMutation(10.0, 2.0)
am(p, skf)

(array([[ 8.517385 ,  9.101417 ,  8.417903 , 10.       ,  9.942884 ],
        [10.       ,  9.995075 , 10.       , 10.       , 10.       ],
        [ 9.674025 ,  8.186938 ,  8.347168 , 10.       ,  8.757153 ],
        [ 8.877822 ,  8.050218 , 10.       , 10.       ,  9.124175 ],
        [ 8.094106 , 10.       , 10.       , 10.       , 10.       ],
        [10.       , 10.       ,  9.505994 , 10.       ,  9.325687 ],
        [10.       , 10.       , 10.       , 10.       , 10.       ],
        [ 9.450962 ,  8.971153 ,  8.453933 , 10.       ,  9.097835 ],
        [10.       ,  8.725991 , 10.       ,  8.5836525, 10.       ],
        [10.       , 10.       , 10.       , 10.       , 10.       ]],
       dtype=float32),
 array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1], dtype=int32))

In [14]:
crs = ArithmeticCrossover()
rmp = NormalRMP()

crs(rmp(10), p, p, skf, skf)

(array([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]),
 array([0, 1, 0], dtype=int32))

In [4]:
rmp(5)

array([0.3, 0.3, 0.3, 0.3, 0.3])