In [23]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))
gnbg_tasks.append(GNBGTask(6, 100))

In [25]:
cec2017_tasks = get_10_tasks()

In [17]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [32]:
num_indis_per_task = 150
indi_len = 50
crossover = BLXCrossover()
mutation = PolynomialMutation(20)
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 114482.51926269832
Mean Fitness: 167784.05604831627

Task 1:
Best Fitness: 335574.8914666791
Mean Fitness: 481372.02768145304

Task 2:
Best Fitness: 306897.28026785114
Mean Fitness: 484925.16889512894

Task 3:
Best Fitness: 40.124796057525444
Mean Fitness: 50.0338892123428

Task 4:
Best Fitness: 2817607877.410504
Mean Fitness: 6208366861.687385

Task 5:
Best Fitness: 21.397894819186885
Mean Fitness: 21.702409978298956

Task 6:
Best Fitness: 84.59562723251032
Mean Fitness: 99.58811954883434

Task 7:
Best Fitness: 17333.362894304624
Mean Fitness: 20872.45990985499

Task 8:
Best Fitness: 94.98253020181201
Mean Fitness: 126.00668470912987

Task 9:
Best Fitness: 75033.3877564581
Mean Fitness: 122934.65573407854



In [33]:
bfs, mfs = amfea.fit(num_gen=5000, monitor=True, monitor_rate=500)

Gen 0
Task 0, Best: 106850.1328125, Avg: 159522.60973526852
Task 1, Best: 335574.8914666791, Avg: 450348.8831368544
Task 2, Best: 306897.28026785114, Avg: 453804.0854417755
Task 3, Best: 40.124796057525444, Avg: 48.241178219970365
Task 4, Best: 2817607877.410504, Avg: 5578446477.86148
Task 5, Best: 21.397894819186885, Avg: 21.662159402649134
Task 6, Best: 84.59562723251032, Avg: 97.67570680929033
Task 7, Best: 17333.362894304624, Avg: 20221.36949494692
Task 8, Best: 88.37026977539062, Avg: 118.70193262105357
Task 9, Best: 74459.64455723815, Avg: 113637.92531715962
Time taken each gen: 0.0483 seconds

Gen 500
Task 0, Best: 3451.15283203125, Avg: 5052.222409725525
Task 1, Best: 2765.552440500662, Avg: 3631.201165668665
Task 2, Best: 2834.22802734375, Avg: 3551.3720574937056
Task 3, Best: 14.23593807220459, Avg: 15.321696662425524
Task 4, Best: 5760300.5, Avg: 9242768.10175301
Task 5, Best: 12.672261238098145, Avg: 13.593786987272706
Task 6, Best: 35.50753912550228, Avg: 40.73380930877558

In [28]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.92707397e-01 9.28115568e-01 1.95030332e-01 9.19464883e-01
 7.00052070e-01 1.94086735e-01 9.32649332e-01 2.01325155e-01
 3.79375448e-01 6.99848299e-01 1.94312757e-01 1.91218354e-01
 9.32632332e-01 7.04786795e-01 1.85863576e-01 2.03263489e-01
 6.95277561e-01 9.17992806e-01 9.40317772e-01 9.22242633e-01
 7.15224694e-01 2.01667188e-01 7.00697586e-01 1.83446501e-01
 7.04126343e-01 1.93066440e-01 7.03597835e-01 9.20387664e-01
 7.05086955e-01 7.20233286e-04 7.07544023e-01 9.28164487e-01
 1.85552661e-01 1.80195522e-01 2.14168065e-01 1.89942223e-01
 7.02260894e-01 7.04083201e-01 9.23887402e-01 3.15534153e-03
 9.19865290e-01 7.02337478e-01 9.06982242e-01 9.22580845e-01
 6.97567082e-01 7.06233374e-01 7.08674613e-01 1.98085688e-01
 9.28875413e-01 1.99998422e-01]
[6637.95167233]


In [31]:
print(np.max(amfea.pop))

0.9795161081006124


In [7]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [9]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([22735.02372398])

In [199]:
print(x_test)

[0.37138179 0.73449412 0.36311813 0.78244749 0.99178212 0.47985734
 0.36771698 0.51114184 0.04594897 0.84181967 0.61995408 0.63615412
 0.46263011 0.8640062  0.14332885 0.62474759 0.54728951 0.59178973
 0.36934856 0.98753811 0.03777077 0.29882631 0.96237095 0.15249977
 0.7886243  0.27673331 0.88030284 0.30618377 0.50073916 0.18406873
 0.35633323 0.47317796 0.91791397 0.80261628 0.74382469 0.86932051
 0.35167865 0.03108078 0.88207472 0.64581258 0.17599662 0.44207642
 0.74174619 0.14262801 0.26605845 0.89521602 0.44415947 0.62751617
 0.62814485 0.30749574]


In [200]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[152104.57279382]
[425081.00403927]
[519128.14154837]
[53.38544507]
[5.70541367e+09]
[21.72861174]
[104.8360553]
[21254.0220888]
[124.49564953]
[113062.82998873]


In [201]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [109]:
t = np.arange(10)

In [110]:
t = np.array([t, t])
t

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [111]:
t[:, :3]

array([[0, 1, 2],
       [0, 1, 2]])