In [10]:
%load_ext autoreload
%autoreload 2
import numpy as np
from mutation import *
from crossover import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
p = np.full((5, 5), 10.0, dtype=np.float32)
skf = np.random.randint(0, 2, 5)
am = AdditiveMutation(10.0, 2.0)
am(p, skf)

(array([[10.       ,  8.539509 ,  9.31688  , 10.       , 10.       ],
        [10.       ,  8.016278 ,  8.337529 ,  8.827667 ,  9.661642 ],
        [ 9.245015 ,  9.029444 ,  8.610632 , 10.       , 10.       ],
        [ 9.20727  ,  9.151408 , 10.       , 10.       ,  9.7848835],
        [ 8.517543 , 10.       , 10.       , 10.       ,  8.414768 ]],
       dtype=float32),
 array([1, 1, 1, 0, 0], dtype=int32))

In [22]:
crs = ArithmeticCrossover()
rmp = np.random.uniform(size=5)
crs(rmp, p, p, skf, skf)

(array([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]),
 array([1, 1, 0], dtype=int32))