In [15]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
import os
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [59]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1, 100))
gnbg_tasks.append(GNBGTask(2, 100))
gnbg_tasks.append(GNBGTask(3, 100))
gnbg_tasks.append(GNBGTask(4, 100))
gnbg_tasks.append(GNBGTask(5, 100))
gnbg_tasks.append(GNBGTask(6, 100))

In [16]:
cec2017_tasks = get_10_tasks()

In [17]:

API_KEY = os.getenv("DEEPSEEK_API_KEY")
print(API_KEY)


sk-505a4ff57cfb432d8888a3d8d66a3133


In [18]:
num_indis_per_task = 100
indi_len = 50
crossover = BLXCrossover()
mutation = PolynomialMutation(20)
rmp = NormalRMP(0.3)

amfea = AMFEA(num_indis_per_task, indi_len, cec2017_tasks, crossover, mutation, rmp)

Initialization:
Task 0:
Best Fitness: 105140.88584214126
Mean Fitness: 163065.50441816394

Task 1:
Best Fitness: 345572.8969148513
Mean Fitness: 489789.8467053779

Task 2:
Best Fitness: 310822.29785084375
Mean Fitness: 483559.6303278146

Task 3:
Best Fitness: 38.04149393998023
Mean Fitness: 50.126422476820906

Task 4:
Best Fitness: 3427897225.032406
Mean Fitness: 6107616252.852589

Task 5:
Best Fitness: 21.493663088101606
Mean Fitness: 21.69586188843458

Task 6:
Best Fitness: 86.9487274521891
Mean Fitness: 99.70689012195444

Task 7:
Best Fitness: 18322.498992970857
Mean Fitness: 21266.1423148897

Task 8:
Best Fitness: 86.85194464607254
Mean Fitness: 123.70212973633848

Task 9:
Best Fitness: 85106.08666504062
Mean Fitness: 122873.56374540854



In [19]:
bfs, mfs = amfea.fit(num_gen=3000, monitor=True, monitor_rate=500)

Gen 0
Task 0, Best: 105140.88584214126, Avg: 155708.54853176896
Task 1, Best: 345572.8969148513, Avg: 470593.1788952332
Task 2, Best: 308950.05414336594, Avg: 461360.94439130224
Task 3, Best: 38.04149393998023, Avg: 48.81505995255585
Task 4, Best: 3427897225.032406, Avg: 5754318025.63321
Task 5, Best: 21.452653884887695, Avg: 21.659340736703587
Task 6, Best: 86.63593365327733, Avg: 97.61910450420254
Task 7, Best: 17940.827857664008, Avg: 20858.290656308018
Task 8, Best: 86.85194464607254, Avg: 118.2762573087054
Task 9, Best: 85106.08666504062, Avg: 118552.29564196365
Time taken each gen: 0.0232 seconds

Gen 500
Task 0, Best: 5469.33642578125, Avg: 6952.350365056931
Task 1, Best: 7753.964532503914, Avg: 8864.18007201471
Task 2, Best: 6513.545433654372, Avg: 7233.16741150847
Task 3, Best: 11.479818344116211, Avg: 12.764178734358563
Task 4, Best: 11392994.003763817, Avg: 19362772.5443883
Task 5, Best: 20.609115600585938, Avg: 20.91581432278169
Task 6, Best: 37.33964920043945, Avg: 39.3452

In [20]:
for i in range(len(amfea.pop[:701])):
    if amfea.skill_factor[i] == 7:
        x = amfea.pop[i]
        print(x)
        print(SchwefelTask.fitness(np.array([x])))

[1.93226010e-01 7.05807714e-01 1.97883578e-01 7.03117826e-01
 2.01943363e-01 7.08599583e-01 1.95950180e-01 1.97053421e-01
 1.96125771e-01 2.08825152e-01 7.02835703e-01 7.06219148e-01
 7.06340576e-01 9.25316851e-01 7.10067368e-01 3.71740729e-01
 2.01996833e-01 9.25353214e-01 1.98465528e-01 7.04884229e-01
 9.18473708e-01 2.07689387e-01 1.93640701e-01 1.96970362e-01
 9.23907897e-01 9.16209203e-01 6.98650607e-01 6.15603846e-04
 2.01893547e-01 1.93868424e-01 9.28189062e-01 9.17710729e-01
 9.18144031e-01 5.61083988e-01 7.10153267e-01 7.04537242e-01
 1.91502793e-01 7.04257774e-01 1.97831264e-01 6.60488721e-04
 1.95483098e-01 9.23591563e-01 9.09038354e-01 7.09959836e-01
 2.05119545e-01 6.96381445e-01 1.97751252e-01 2.04578163e-01
 1.96389047e-01 2.00386440e-01]
[6922.64299878]


In [22]:
print(np.max(amfea.pop))

1.0


In [7]:
dim = 50
schwefel_shift = np.full(dim, 0)
schwefel = Schwefel(50, schwefel_shift)

In [9]:
x_test = np.random.uniform(0, 1, size=dim)
SchwefelTask = CEC17Task(schwefel, 500)
SchwefelTask.fitness(np.array([x_test]))

array([22735.02372398])

In [199]:
print(x_test)

[0.37138179 0.73449412 0.36311813 0.78244749 0.99178212 0.47985734
 0.36771698 0.51114184 0.04594897 0.84181967 0.61995408 0.63615412
 0.46263011 0.8640062  0.14332885 0.62474759 0.54728951 0.59178973
 0.36934856 0.98753811 0.03777077 0.29882631 0.96237095 0.15249977
 0.7886243  0.27673331 0.88030284 0.30618377 0.50073916 0.18406873
 0.35633323 0.47317796 0.91791397 0.80261628 0.74382469 0.86932051
 0.35167865 0.03108078 0.88207472 0.64581258 0.17599662 0.44207642
 0.74174619 0.14262801 0.26605845 0.89521602 0.44415947 0.62751617
 0.62814485 0.30749574]


In [200]:
super_tasks = get_10_tasks()
for task in super_tasks:
    print(task.fitness(np.array([x_test])))

[152104.57279382]
[425081.00403927]
[519128.14154837]
[53.38544507]
[5.70541367e+09]
[21.72861174]
[104.8360553]
[21254.0220888]
[124.49564953]
[113062.82998873]


In [201]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)
f.close()

In [109]:
t = np.arange(10)

In [110]:
t = np.array([t, t])
t

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [111]:
t[:, :3]

array([[0, 1, 2],
       [0, 1, 2]])