In [12]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pickle
from mutation import *
from crossover import *
from rmp import *
from mfea import *
from task import *
from llm import *
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
gnbg_tasks = []
gnbg_tasks.append(GNBGTask(1))
gnbg_tasks.append(GNBGTask(2))

In [22]:
num_p = 10
dim = 30
p1 = np.random.uniform(-100, 100, size=(num_p, dim))
p2 = np.random.uniform(-100, 100, size=(num_p, dim))
p1_skill_factor = np.random.randint(0, 2, size=num_p)
p2_skill_factor = np.random.randint(0, 2, size=num_p)

In [23]:
crossover = BLXCrossover()
rmp = np.full(num_p, 0.3)
print(rmp)
crossover(rmp, p1, p2, p1_skill_factor, p2_skill_factor, eval=True, tasks=gnbg_tasks)

[0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
[172888.55685904 133094.34811231]
[181293.3318297  117172.32722328]
[-701.28938563 -701.28363527 -701.27944396]
[-701.3004037  -701.31347065 -701.32389222]


(array([[-4.82388927e+01, -5.09158388e+01, -1.15522376e+02,
         -4.69821016e+01, -9.10965835e+01, -6.26577335e+01,
         -7.54846654e+01, -6.52608865e+01, -3.88731407e+01,
         -3.11310466e+01,  6.87797956e+00, -1.35682462e+01,
          6.63749361e+01, -4.09016404e+01,  3.27151464e+01,
         -1.53726055e+02,  4.78168360e+01,  3.99190833e+01,
         -1.41862508e+01, -4.67137283e+01, -3.12529976e+01,
         -4.98014045e+01, -4.49889691e+01, -8.89821375e+01,
         -2.95495206e+01, -7.64686370e+00,  6.20055537e+01,
          6.49664918e+00, -8.25290583e+00,  9.27477242e+01],
        [ 9.99221537e+00,  8.93654931e+01, -8.66805219e+01,
         -6.96458620e+01, -3.78564309e+01, -7.54558903e+01,
         -9.55022916e+01,  4.44002843e+01,  4.69736093e+01,
          9.42941191e+01,  3.92292329e+01,  3.50149145e+01,
         -4.32761064e+01,  8.88475146e+01,  4.42085133e+01,
         -6.64022010e+01,  6.87213457e+01,  3.15935193e+01,
          1.07573913e+02, -3.35087327e+